### ISSUE TITLE
Creating Malformed Transaction

### ISSUE THREAD

**Issue by fix** [LiskHQ/lisk-js#1]
if you use 
```javascript
lisk.transaction.createTransaction(undefined,1000000000,"passphrase","secondpassphrase");
```
you get a malformed transaction (ie with no recipientId)

**Comment by karmacoma** [comment]
Fixed in core, and lisk-dapps-sdk:

- https://github.com/LiskHQ/lisk/commit/eee115402ef011c3026adf742c678c04282c3d73
- https://github.com/LiskHQ/lisk-dapps-sdk/commit/87100e1299c02b06516ead68c7ef91a9ed03ec1d
