### ISSUE TITLE
Remove dapp API endpoints

### ISSUE THREAD

**Issue by Tosch110** [LiskHQ/lisk-js#106]
Remove dapp API endpoints for the coming redesign and SDK stabilization.

Current behaviour:
It is possible to submit dapp transactions via `lisk-js`.

Expected behaviour:
It should not be possible to submit current dapp transactions with `lisk-js`.

In detail:
`install`, `uninstall`, `start/stop` dapps should be disabled.

**Comment by karmacoma** [comment]
This is the related to issue in Lisk Core: https://github.com/LiskHQ/lisk/issues/560

**Comment by karmacoma** [comment]
Closed by: https://github.com/LiskHQ/lisk-js/pull/252
