### ISSUE TITLE
lisk.api({testnet:true}) doesn't work

### ISSUE THREAD

**Issue by slaweet** [LiskHQ/lisk-js#119]
### Expected behaviour
```
lisk.api({testnet:true})
```
should connect to a testnet node, such as `testnet.lisk.io:7000`
### Actual behaviour
```
lisk.api({testnet:true})
```
tries to connect to `testnet.lisk.io:8000`
### Steps to reproduce
```
lisk.api({testnet:true})
```

Note that
```
let node = lisk.api();
node.setTestnet(true);
```
actually works:
https://github.com/LiskHQ/lisk-js/blob/development/lib/api/liskApi.js#L160-L172

**Comment by karmacoma** [comment]
Closed by: #120
