### ISSUE TITLE
Enable Eslint on tests

### ISSUE THREAD

**Issue by Tosch110** [LiskHQ/lisk-js#126]
Eslint should also be checking for the tests to have the Lisk coding standards.

**Comment by miktam** [comment]
do you need help with this?

**Comment by alepop** [comment]
Eslint already checks the test files. 
`Gruntfile.js`
```
eslint: {
	options: {
		configFile: 'eslint_ecma5.json',
		reset: true
	},
	target: ['lib/**', 'test/**', '!test/mocha.opts', 'Gruntfile.js', 'index.js']
},
```
Or you mean to run eslint before tests?

**Comment by miktam** [comment]
@alepop just wanted to help. if tests are already being linted, great!

**Comment by karmacoma** [comment]
Closing issue as tests are already added as a target, and are being executed prior to running tests during travis build.
