### ISSUE TITLE
Remove ES6 syntax from dist

### ISSUE THREAD

**Issue by willclarktech** [LiskHQ/lisk-js#148]
Somehow there's non-ES5 syntax in `dist/lisk-js.js` on line 476:
```
requestParams: { transaction }
```

If this file was automatically generated, we'll need to make sure it's not going to happen again.

**Comment by Tosch110** [comment]
Yes, I remember having this in the code. This issue indicates that the distributed version is not correctly browserified and uglyfied with the branches accordingly. We should emphasize this for every merged Pull Request

**Comment by willclarktech** [comment]
This was due to an ES6 feature here: https://github.com/LiskHQ/lisk-js/blob/189-test_common/lib/utils/mnemonic.js#L44

Should be fixed once https://github.com/LiskHQ/lisk-js/pull/194 is merged.

**Comment by Tosch110** [comment]
#194 is merged and this is fixed. Thanks
