### ISSUE TITLE
Send request with promise failing non-deterministically

### ISSUE THREAD

**Issue by willclarktech** [LiskHQ/lisk-js#157]
This test fails some of the time locally and on CI:
https://github.com/LiskHQ/lisk-js/blob/development/test/api/liskApi.js#L1006

```
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property 'should' of undefined
```

https://travis-ci.org/LiskHQ/lisk-js/builds/249699843?utm_source=github_status&utm_medium=notification

**Comment by alepop** [comment]
@willclarktech I think that these `HTTP` requests need to be mocked like these #123

**Comment by Tosch110** [comment]
Yes, I agree

**Comment by Tosch110** [comment]
This issue is not applicable anymore.
