### ISSUE TITLE
Allow transaction objects to be generated with pubKey instead of address

### ISSUE THREAD

**Issue by Isabello** [LiskHQ/lisk-js#203]
Currently, in order to create a transaction we must pass the address of the recipientId. It would be nice if we could alternatively pass the publickey, and Lisk-JS would subsequently generate the address for us and create the transaction as normal. In this way, we could send "directly" to publickeys without an address on hand.

**Comment by Tosch110** [comment]
This can be done, I would actually prefer if core would adapt sending to publicKey!
