### ISSUE TITLE
Add license headers to all files

### ISSUE THREAD

**Issue by willclarktech** [LiskHQ/lisk-js#211]
For legal reasons, this header template should be added to the top of all significant files (with comment characters replaced as necessary):
```
# LiskHQ/lisk-js
# Copyright (C) 2017 Lisk Foundation
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
######################################################################
```
We should also make sure that the distribution files contain this after the build process.

**Comment by vikramnr** [comment]
@willclarktech  Is this waiting to be fixed? If so what has to be done.

**Comment by willclarktech** [comment]
Hi @vikramnr, I've updated the issue description. Are you interested in contributing?

**Comment by vikramnr** [comment]
@willclarktech  Yeah sure. Which files this has to be added?

> significant files

**Comment by willclarktech** [comment]
@Isabello Can you provide a criterion here?

**Comment by Isabello** [comment]
All files except for ones used for configuration (.json), CI (Jenkinsfile), opts (mocha) and code that is not explicitly ours, such as bitcoin-core files

**Comment by Tosch110** [comment]
We already have license headers.

**Comment by willclarktech** [comment]
@vikramnr Sorry for the confusion, this issue was opened in response to a general decision about all our repositories, without looking at the specific situation of `lisk-js`.

**Comment by vikramnr** [comment]
@willclarktech  No problem 👍

**Comment by Tosch110** [comment]
Still we have realised it is not consistent on all the files! So we could update this issue accordingly
