### ISSUE TITLE
Create browser dist files

### ISSUE THREAD

**Issue by willclarktech** [LiskHQ/lisk-js#237]
In a special branch of its own.

Should also solve #323

**Comment by Tosch110** [comment]
https://github.com/LiskHQ/lisk-js/tree/browser

**Comment by willclarktech** [comment]
I would prefer a cleaner branch that only has the dist files in.

**Comment by willclarktech** [comment]
@Tosch110 We can use `git subtree` (and ideally store it in an npm script) e.g.:
`git subtree push -P dist-browser origin browser`
