### ISSUE TITLE
gitcdn.xyz -> 404: Not Found

### ISSUE THREAD

**Issue by karek314** [LiskHQ/lisk-js#323]
[https://gitcdn.xyz/repo/LiskHQ/lisk-js/development/dist/lisk-js.js](https://gitcdn.xyz/repo/LiskHQ/lisk-js/development/dist/lisk-js.js)
redirects to
[https://gitcdn.xyz/cdn/LiskHQ/lisk-js/97296fa7414cb68b4002a3689feb3cc6b6a73b7b/dist/lisk-js.js](https://gitcdn.xyz/cdn/LiskHQ/lisk-js/97296fa7414cb68b4002a3689feb3cc6b6a73b7b/dist/lisk-js.js)
ends up with
`404: Not Found`

**Comment by willclarktech** [comment]
Thanks for reporting. This should be addressed in https://github.com/LiskHQ/lisk-js/issues/237

**Comment by Tosch110** [comment]
Solved in https://github.com/LiskHQ/lisk-js/pull/326
