### ISSUE TITLE
Inconsistency in vote

### ISSUE THREAD

**Issue by karek314** [LiskHQ/lisk-js#335]
Why does [voting](https://github.com/LiskHQ/lisk-js/blob/development/src/transactions/vote.js#L41) require address to be specified while [second signature creation](https://github.com/LiskHQ/lisk-js/blob/development/src/transactions/signature.js#L53) or [delegate registration](https://github.com/LiskHQ/lisk-js/blob/development/src/transactions/delegate.js#L41) not?

**Comment by willclarktech** [comment]
Very good question - amount is always 0 so `recipientId` is irrelevant.

**Comment by Tosch110** [comment]
I agree that recipientId should also be null in a vote transaction.

So far it is required by core to work like this: 
https://github.com/LiskHQ/lisk/blob/a0763853b67b25cd17e0fb62c967793cc7093a2e/logic/vote.js#L64-L66

Maybe I am missing a point but imo it should be `null` as in the referred transactions.
