### ISSUE TITLE
experiment.html?#encrypt / #decrypt doesn't work

### ISSUE THREAD

**Issue by karek314** [LiskHQ/lisk-js#340]
https://liskhq.github.io/lisk-js/example/experiment.html?#encrypt
button "sign" does nothing for correctly filled data

https://liskhq.github.io/lisk-js/example/experiment.html?#decrypt
button "decrypt" reloads website for correctly filled data

Both do not provide any result. Tested on latest Chrome and Safari on macOS.

**Comment by willclarktech** [comment]
Thanks for reporting, we need to change the experiment script to load from `master` instead of `development`.

**Comment by willclarktech** [comment]
Actually this will change after https://github.com/LiskHQ/lisk-js/issues/237

**Comment by Tosch110** [comment]
Those pages will go away in 1.0 anyway. 
Maybe there will be a repository at one point to have such a GUI for lisk-js to do basic things online or offline. But for now experiment page will be deprecated.
