### ISSUE TITLE
Make module export pattern consistent

### ISSUE THREAD

**Issue by willclarktech** [LiskHQ/lisk-js#349]
Right now we have
```js
export function ...
export default ...
module.exports = ...
```

**Comment by alepop** [comment]
what wrong with using both patterns `export default` and `export something`?

**Comment by willclarktech** [comment]
@alepop Nothing per se, but sometimes we're exporting a default object which just contains a bunch of functions, where it might make more sense to just export the functions directly. This issue is mostly about setting a standard and making sure we're following it consistently, which is something we haven't done since migrating from ES5 to ES6.
