### ISSUE TITLE
(1.0.0) API methods not creating signed transactions

### ISSUE THREAD

**Issue by mfressdorf** [LiskHQ/lisk-js#358]
I expect PUT/POST API Methods to still create requests with signed transaction objects.

Instead the current implementation of the sendRequestPromise Method does not support the mapping of transaction objects anymore. This was part of the [checkOfflineRequestBefore Method](https://github.com/LiskHQ/lisk-js/blob/d510e7225358630a371c01936299087f93fa92ba/lib/api/parseTransaction.js#L69) utilized in the [changeRequest method](https://github.com/LiskHQ/lisk-js/blob/61b4abd849cd4817cda31fe0cc4267c4e413bc96/src/api/privateApi.js#L209) which is now missing on the sendRequestPromise method

see here (before): 
https://github.com/LiskHQ/lisk-js/blob/61b4abd849cd4817cda31fe0cc4267c4e413bc96/src/api/privateApi.js#L278

and here (after): 
https://github.com/LiskHQ/lisk-js/blob/development/src/api/privateApi.js#L225

The current createRequestObject method used by sendRequestPromise does not have this functionality.

**Comment by willclarktech** [comment]
1.0.0 will be a major (breaking) release. There are many changes to the public and private functionality. `sendRequestPromise` is a private function which has been refactored to handle only one thing: sending requests. Previously it mixed various concerns.

Going forward there are functions for creating and signing every type of transaction, and a public function for broadcasting a signed transaction. There is also a public function for sending arbitrary requests. Is there some functionality you think is missing from this picture?

**Comment by mfressdorf** [comment]
Thank you for clarifying this! Coming from lisk-nano (which makes heavy use of the old API) this got me a bit confused. But since lisk-nano will adjust the call signature in 2.0.0 accordingly, this feels a lot more straightforward now and will incidentally also simplify an integration of ledger-nano-s.

**Comment by willclarktech** [comment]
OK to close?
