### ISSUE TITLE
TypeError: "list" argument must be an Array of Buffers

### ISSUE THREAD

**Issue by karek314** [LiskHQ/lisk-js#414]
As per tests - https://github.com/LiskHQ/lisk-js/commit/ca2025f4c53739266ba432566512aa01748dd3a0#diff-0d60bb50d44befa190a91ff06388f42fR266

Example below should work
```
var cipherAndNonce = {cipher: '1c527b9408e77ae79e2ceb1ad5907ec523cd957d30c6a08dc922686e62ed98271910ca5b605f95aec98c438b6214fa7e83e3689f3fba89bfcaee937b35a3d931640afe79c353499a500f14c35bd3fd08',iv: '89d0fa0b955219a0e6239339fbb8239f',};
var decrypted = lisk.crypto.decryptPassphraseWithPassword(cipherAndNonce, "myTotal53cr3t%&");
```
But instead i'm getting "TypeError: "list" argument must be an Array of Buffers".
Tested in browser. tried both lisk-js.min.js and lisk-js.js.

Encryption works fine.

**Comment by Tosch110** [comment]
I cannot reproduce this error. If you still have this error, please reopen or file an issue with more information as described in https://github.com/LiskHQ/lisk-js/blob/1.0.0/ISSUE_TEMPLATE.md
Most importantly which version you are using and if in the browser or on node.
