### ISSUE TITLE
Improve mocha failure output in cypress browser tests

### ISSUE THREAD

**Issue by willclarktech** [LiskHQ/lisk-js#419]
In the rare case that we get a browser test failing on ci but not locally, https://github.com/LiskHQ/lisk-js/pull/406 gives us the mocha-generated html for the failing test. The tests are also available on the `window.mocha`, but extracting them is not as simple as expected. This should loop through and get all the failing tests regardless of depth:

```js
const combineArrays = (accumulator, next) => [...accumulator, ...next];

const hasFailedState = ({ state }) => state === 'failed';

const processTests = tests => tests
	.filter(hasFailedState)
	.map(({ err, title }) => ({
		err,
		title,
	}));

const getFailedTests = ({ suites, tests, _beforeAll, _beforeEach, _afterEach, _afterAll }) => {
	const nestedTests = suites
		.map(getFailedTests)
		.reduce(combineArrays, []);

	return [
		...processTests(_beforeAll),
		...processTests(_beforeEach),
		...processTests(_afterEach),
		...processTests(_afterAll),
		...processTests(tests),
		...processTests(nestedTests),
	];
};

const throwFailuresInWindow = (win) => {
	// ...
	if (failures.length) {
		throw getFailedTests(win.mocha.suite);
	}
};
```

For some reason the `.map` call in `processTests` results in an empty array being thrown even when there are failures (removing it results in an array of huge mocha failing test objects).

**Comment by Tosch110** [comment]
It would also help to try a different approach where we just get rid of the annoying html output by some regex or whatever comes handy.

**Comment by Tosch110** [comment]
We are fine with the current solution.
