### ISSUE TITLE
Migrate from browserify to webpack

### ISSUE THREAD

**Issue by yasharAyari** [LiskHQ/lisk-js#443]
You need to remove browserify and grunt and use webpack instead of both of them.because of so many reasons:
1. webpack has better community than browserify
2. you can use it as your task runner and remove grunt
3. Webpack already provides options for minification and sourcemaps for your bundle
4. Webpack can be run as middleware through a custom server called webpack-dev-server
5. Webpack has a powerful watch mode

**Comment by willclarktech** [comment]
Closing until more concrete benefits can be elucidated: 1 is nebulous, 2 merely mitigates the cost of switching rather than offering a reason to switch, 3–5 provide no added value to what we have already in place.
