### ISSUE TITLE
Add an automated check for node distribution

### ISSUE THREAD

**Issue by willclarktech** [LiskHQ/lisk-js#466]
Currently we have automated tests for source code and for browserified code, but have to manually check the node distribution.

**Comment by Tosch110** [comment]
Yes, in summary the `dist-node` is compiled with babel and therefore different. It would be nice to have a check if that code passes the tests the same way as the source code.

**Comment by Tosch110** [comment]
Adding a bash script copy -/ replace the import before tests start

**Comment by Tosch110** [comment]
How about we do it the other way around and always run the tests against the build? I guess we can assume that it works the same way we do now but can potentially catch errors in the production build.

**Comment by willclarktech** [comment]
@Tosch110 Doing it this way would drastically slow down the process of TDD.

**Comment by Tosch110** [comment]
How drastically do you mean? For me the build takes less than a second.

**Comment by willclarktech** [comment]
I use `npm run test:watch` and save frequently. An extra second added to every test run would be a real problem for me.

**Comment by shuse2** [comment]
I haven't check it thorough, but
`https://www.npmjs.com/package/babel-plugin-module-resolver`
might solve the problem.

if we create alias, and run test with changing the root, we might be able to solve the problem.
