### ISSUE TITLE
Docs for printSignedMessage are outdated

### ISSUE THREAD

**Issue by slaweet** [LiskHQ/lisk-js#472]
### Expected behaviour
`Lisk.crypto.printSignedMessage` in lisk-js 0.5 returns:
```
-----BEGIN LISK SIGNED MESSAGE-----
-----MESSAGE-----
<message>
-----PUBLIC KEY-----
<publicKey>
-----SIGNATURE-----
<signature>
-----END LISK SIGNED MESSAGE-----
```

### Actual behaviour
The docs say:
https://github.com/LiskHQ/lisk-js/blob/26c50c30d6f6af706efa2a808f9104f80f94d24f/docs/example/api.html#L973-L978

**Comment by willclarktech** [comment]
This will change also in 1.0.0
