### ISSUE TITLE
Improve communication of headers

### ISSUE THREAD

**Issue by Tosch110** [LiskHQ/lisk-js#475]
- [ ] Consistency in capital naming (nethash)
- [ ] Rename functions and objects that are about headers rather than nethash
- [ ] See how much we can strip out / update on the headers
- [ ] Move nethash into constants
- [ ] Get rid of broadhash
- [ ] Structure of the returned object (netHashOptions)

**Comment by willclarktech** [comment]
@Tosch110 I think we can close this as it should now be covered as part of https://github.com/LiskHQ/lisk-js/issues/491
