### ISSUE TITLE
Update API to 1.0.0 finalised version

### ISSUE THREAD

**Issue by willclarktech** [LiskHQ/lisk-js#482]
Since we refactored the API, there have been some changes to the specification that we should reflect in LiskJS.

**Comment by diego-G** [comment]
A new version is just been published https://app.swaggerhub.com/apis/LiskHQ/Lisk/1.0.23

**Comment by shuse2** [comment]
@diego-G thanks for the info!

**Comment by diego-G** [comment]
Another version has been bumped https://app.swaggerhub.com/apis/LiskHQ/Lisk/1.0.24
