### ISSUE TITLE
Mock time passing in handleSendRequestFailures tests

### ISSUE THREAD

**Issue by willclarktech** [LiskHQ/lisk-js#485]
These tests currently take over 5s but we should be able to use sinon timers to make them much faster

**Comment by alepop** [comment]
@willclarktech maybe the problem in this timeout? 
https://github.com/LiskHQ/lisk-js/blob/00dd4ea3df3c879d57e434ac79ca52eb50924e6a/src/api/privateApi.js#L213
why did you add a 1s delay?

**Comment by willclarktech** [comment]
@alepop Yep, that's the source of the delay. It was originally a request from the nano team to retry requests in case a node is uncontactable for a moment. This issue is not about removing this functionality.

Just because we have a 1 second wait in production time, it doesn't mean we necessarily have to wait 1 second in test time. This issue is about finding out whether we can use sinon timers to speed up the test run, and to implement that if so.
