### ISSUE TITLE
Using lisk in the browser

### ISSUE THREAD

**Issue by marijnbent** [LiskHQ/lisk-js#518]
I'm in the 1.0.0 branch.

When opening index.html in the browser, I get the following message in the console. Any thoughts how to solve this? 

Refused to execute script from 'http://localhost:63342/lisk-js/dist-browser/lisk-js.min.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

This should solve it, but would this be desirable?
https://stackoverflow.com/a/27267752

**Comment by Tosch110** [comment]
Hi @marijnbent 

from the links you post I can assume that you have some local server running which serves the files. Can you describe a little more of your setup? 

You should be able to use the file directly in your browser (index.html)

**Comment by Tosch110** [comment]
No additional information, I am assuming this will get closed by https://github.com/LiskHQ/lisk-js/issues/515

If not, please reopen this issue with some more information. Thanks
