### ISSUE TITLE
Remove support for callbacks

### ISSUE THREAD

**Issue by willclarktech** [LiskHQ/lisk-js#527]
In some places we support both promises and callbacks. E.g.

https://github.com/LiskHQ/lisk-js/blob/1.0.0/src/api/liskApi.js#L141

It would be less confusing to support only promises.

**Comment by Tosch110** [comment]
Quick question, would this be dependend upon, get in the way or helpful for https://github.com/LiskHQ/lisk-js/pull/512 ?

**Comment by willclarktech** [comment]
@Tosch110 It would probably make #512 easier, but I don't think there would be many conflicts.
