### ISSUE TITLE
Remove babel-register compiler from mocha.opts

### ISSUE THREAD

**Issue by willclarktech** [LiskHQ/lisk-js#532]
It's redundant since we run mocha with nyc, which already uses babel-register.

**Comment by willclarktech** [comment]
This would actually make it less convenient to run individual files on a one-off basis via `./node_modules/.bin/mocha` (or subsequently `npx mocha`).

**Comment by Tosch110** [comment]
Okay, then it is helpful and not redundant. Thanks for finding this.
