### ISSUE TITLE
Tests for convertPublicKeyEd2Curve/convertPrivateKeyEd2Curve not using Buffers

### ISSUE THREAD

**Issue by robladbrook** [LiskHQ/lisk-js#551]
This is a really minor issue that only impacts the tests because the non-test code is calling these methods correctly.

### Expected Behaviour 
Calls to `convertPublicKeyEd2Curve` and `convertPrivateKeyEd2Curve` expect a byte array / Buffer of the key

E.g.

`convertPrivateKeyEd2Curve(Buffer.from(defaultPrivateKey, 'hex'))`

### Actual Behaviour
The tests are passing the key as a string which means the NaCl code is evaluating each character within the string as if it were a byte array. This is incorrect and invalidates the tests.

https://github.com/LiskHQ/lisk-js/blob/1.0.0/test/crypto/convert.js#L121

**Comment by willclarktech** [comment]
Nice catch @robladbrook, thank you.
