### ISSUE TITLE
Refactor constructor of LiskAPI

### ISSUE THREAD

**Issue by shuse2** [LiskHQ/lisk-js#588]
### Description

Limit the constructor options to what actually needed.

#### Change name
`LiskAPI` => `HttpClient`

#### Limit constructor options
nodes: [string] (required)
nethash: string (required)
node: string default select from nodes
bannedNodes: [string] default []
verion: string default 1.0.0
minVersion: string default 1.0.0
randomizeNode: boolean default true

#### Add factory method
- Add getLiskMainnetHttpClient()
- Add getLiskTestnetHttpClient()
which returns a new HTTP client instance with each settings.

#### Separate headers
- `version`, `minVersion` and `nethash` is the only thing should be changed for headers
#### ssl/testnets and default settings
- `ssl` and `testnet` should be indicated by `nodes` (e.g. ['https://testnet.io:443`, 'http://testnet.io:7001'])
- it is a library, so it should not depends on `config.json`, it should be default constants.

### Versions

v1.0.0 branch

**Comment by willclarktech** [comment]
Prefer `HTTPClient`?
