### ISSUE TITLE
lisk.api().listTransactions(address, callback) send unexpected random param

### ISSUE THREAD

**Issue by slaweet** [LiskHQ/lisk-js#60]
steps to replicate:
> address = '16313739661670634666L'
> callback = function (data) { console.log(data);}
> lisk.api({node:'localhost', port: 4000}).listTransactions(address, callback);
VM332:1 Object {success: false, error: "Failed to get transactions: Parameter is not supported: random"}
> lisk.api().listTransactions(address, callback);
VM332:1 Object {success: false, error: "Failed to get transactions: Parameter is not supported: random"}

**Comment by karmacoma** [comment]
Closed by #66
