### ISSUE TITLE
Rename locateWhitespaces to locateConsecutiveWhitespaces

### ISSUE THREAD

**Issue by Tosch110** [LiskHQ/lisk-js#608]
### Description

passphrase.validation.locateWhitespaces function locates double whitespaces, not all whitespaces as the name would suggest

**Expected behavior:**

Mnemonic passphrases do have whitespaces, but not two following whitespaces, which might happen when users enter their passphrase. The function should throw on two (or more) following whitespaces and indicate that in the name.

**Actual behavior:** 

The function works fine, just the name should indicate what it does.

**Comment by willclarktech** [comment]
How about `locateConsecutiveWhitespaces`?
