### ISSUE TITLE
Transpile distribution to ES5

### ISSUE THREAD

**Issue by karmacoma** [LiskHQ/lisk-js#62]
For reasons of compatibility when running `lisk-js` on older JavaScript compilers, the distribution should be transpiled to the ES5 standard using https://babeljs.io/.

**Comment by wojciak** [comment]
Hi I'm new here, could we use TSC maybe? It's better supported, and transpiles all the way down to es3. It works with normal JS so no need to actually use typescript.

**Comment by Tosch110** [comment]
Hi @wojciak using TSC is in discussion right now. We have not fully decided if we switch and yes, when. If I understand this issue correctly it is about adding babel and support ES6 code but not yet refactoring the whole codebase with ES6 features. As soon as we think about refactoring the codebase to new standards, TypeScript will be discussed intense again. Thanks for your input
