### ISSUE TITLE
Application allows to create a transfer without recipientId

### ISSUE THREAD

**Issue by diego-G** [LiskHQ/lisk-js#624]
### Description

If we create a transfer transaction not passing a recipientId, application accepts it and produces an object with `recipientId` `undefined.

### Steps to Reproduce

1. [First Step]
```
LiskJS.transaction.transfer( { amount: 100000000, passphrase:'wagon stock borrow episode laundry kitten salute link globe zero feed marble' } )
{ amount: '100000000',
  recipientId: undefined,
  senderPublicKey: 'c094ebee7ec0c50ebee32918655e089f6e1a604b83bcaa760293c61e0f18ab6f',
  timestamp: 57708304,
  type: 0,
  fee: '10000000',
  recipientPublicKey: null,
  asset: {},
  signature: '8d450481b1ccf3d84c0579bb91e76497a93ab172ed1dc7c9dd0679beaa0ad26ee2f265e38bf68ce81396ec82fee028363c7311879bfec0ebc04e35222f74390e',
  id: '15458911666823940946' }
```

**Expected behavior:** 

Application gives an exception suggesting to use recipientId.

**Actual behavior:** 

It accepts the request a produced an invalid transaction.

**Reproduces how often:**

Always.

### Versions

`1.0.0`

**Comment by alepop** [comment]
@diego-G is `recipientId` required field in each transaction types? Or it can be empty when we, for example, cast votes or it needs to be equal to sender address like in the current implementation?

**Comment by shuse2** [comment]
In case of transaction types that we don't need `recipientId`, it is sent as empty string.
Related to #620
