### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by Doweig** [LiskHQ/lisk-js#76]
Hello guys, I'm a License newbie as @Isabello knows, so I'm probably wrong.

This module is under the GNU General Public License v3.0 and my understanding is that any project using this code should also be under that same license.

http://stackoverflow.com/questions/3902754/mit-vs-gpl-license

Meaning, for example, that exchanges using it (Poloniex, bittrex, ...) should make their code open source if they are using that module.

Is my understanding of the license correct? Please enlighten me

**Comment by Isabello** [comment]
The answer is on the link you already posted

```
True - in general. You don't *have* to open-source your changes if you're
using GPL. You could modify it and use it for your own purpose as long as
you're not distributing it.
```

They arent distributing their trading tools. So any tools they make that
use lisk-js are not required to be publicised AS LONG AS they do not
distribute them.

**Comment by Doweig** [comment]
Makes sense. Thanks for your answer.
