### ISSUE TITLE
API should hide private methods

### ISSUE THREAD

**Issue by slaweet** [LiskHQ/lisk-js#77]
There are several methods in the lisk-js API that aren't mentioned in the docs, look more like internal utility functions and shouldn't really be used by public, e.g. [sendRequestPromise](https://github.com/liskHQ/lisk-js/blob/development/lib/api/liskApi.js#L185
), getRandomPeer, banNode ...

If we expose these methods, people might use them in their projects and then we have to support them else we break other people's projects. On the other hand, if we make them private we can easily refactor and change their behaviour if necessary in the future.

There are several ways to emulate private methods in JavaScrtipt:
http://stackoverflow.com/questions/55611/javascript-private-methods

**Comment by alepop** [comment]
@slaweet can you type a full list of a private method?

**Comment by slaweet** [comment]
@alepop I'm not so familiar with lisk-js code to easily give a full list. @Tosch110 might be a more suitable person to do that.

**Comment by alepop** [comment]
@slaweet maybe all methods that are not in this [list](https://liskhq.github.io/lisk-js/example/api.html) is private?

**Comment by slaweet** [comment]
@alepop makes sense. If not in documentation then they are private.
